# Another Q-learning tryout on Santa's uncertain bags

We reduce the number of possible states corresponding to 1000 bags to states corresponding to 1 bag. Problem of filling 1000 bags will be translated to the optimal usage of policy and action-value function on varying environment. The last is given by the array of available gifts which decreases when bags are filled.


## States 

A state is characterized by a vector of size `(N_TYPES)`. For example, `s=[1,0,1,0,0,0,0,0,0]`. The initial state is when the null vector or a customly defined vector. Terminal states are defined by state's score. 

How many state there are? There are at most `10^N_TYPES` states.


## Actions

Action is to add a toy to the bag following the list of available toys. For example, action is a integer value corresponding to the toy index.


## Rewards

Action reward can be defined by the score of the bag where a toy has been added.


## Q-learning: Off-Policy Temporal Difference Control

In this algorithm we estimate action-value function $Q(s,a)$ as :
$$
Q(S_t,A_t) \leftarrow Q(S_t,A_t) + \alpha \left[ R_{t+1} + \gamma \max_{a} Q(S_{t+1}, a) - Q(S_t,A_t) \right], \, Q(\cal{S}^{+},a)=0
$$

**Algorithm**
<br>
<div style="background-color: #aaaaaa; padding: 10px; width: 75%; border: solid black; border-radius: 5px;">

    Initialize $Q(s, a)$, for all $s \in \cal{S}$, $a \in \cal{A}(s)$, arbitrarily, and $Q(\text{terminal-state}, \cdot) = 0$<br>
    Repeat (for each episode):<br>
    &emsp;Initialize $S$<br>
    &emsp;Choose $A$ from $S$ using policy derived from $Q$ (e.g., $\epsilon$-greedy)<br>
    &emsp;Repeat (for each step of episode):<br>
    &emsp;&emsp;Take action $A$, observe $R$, $S'$<br>
    &emsp;&emsp;$Q(S,A) \leftarrow Q(S,A) + \alpha \left[ R + \gamma \max_{a}Q(S', a) - Q(S,A) \right]$<br>
    &emsp;&emsp;$S \leftarrow S'; \, A \leftarrow A';$<br>
    &emsp;until $S$ is terminal
</div>

In [1]:
# https://ipython.org/ipython-doc/3/config/extensions/autoreload.html
%load_ext autoreload
%autoreload 2

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from time import time
from copy import deepcopy
import numpy as np
np.random.seed(2017)

from collections import defaultdict
import heapq

import logging
logging.getLogger().setLevel(logging.DEBUG)

In [4]:
import sys
sys.path.append('../common')
from utils import weight3 as weight_fn, weight_by_index
from utils import bag_weight, score, mean_n_sigma, score_stats
from utils import MAX_WEIGHT, AVAILABLE_GIFTS, GIFT_TYPES, N_TYPES, N_BAGS

Compute maximal number of gifts in a terminal state for each product :

$$ (\mathbb{E}[Y] - \text{Var}[Y]^{1/2}) = \text{max_bag_weight}, \, Y=N_i \cdot m_i$$
or 
$$ N_i = \lceil \frac{\text{max_bag_weight}}{\mathbb{E}[X_i] - \text{Var}[X_i]^{1/2}} \rceil$$

In [5]:
LIMIT_STATE = np.zeros((N_TYPES), dtype=np.uint8)
indices = list(range(N_TYPES))
indices.remove(4)
for i in indices:
    weights = [weight_by_index(i) for j in range(50000)]    
    v = np.percentile(weights, 5)
    LIMIT_STATE[i] = int(np.ceil(MAX_WEIGHT/v))
    
v = 24.0741557491
LIMIT_STATE[4] = int(np.ceil(MAX_WEIGHT/v))
    
LIMIT_STATE

array([ 34,  14,   8, 218,   3,  26, 184,  30,  28], dtype=uint8)

In [109]:
fixed_weights = {}
fixed_weights['ball'] = 1.99876912083
fixed_weights['bike'] = 20.0021364556
fixed_weights['blocks'] = 11.6630321858
fixed_weights['book'] = 2.00086596571
fixed_weights['coal'] = 23.7866257713
fixed_weights['doll'] = 4.9993625282
fixed_weights['gloves'] = 1.40310067709
fixed_weights['horse'] = 4.99527064522
fixed_weights['train'] = 10.0234458084
fixed_weights

{'ball': 1.99876912083,
 'bike': 20.0021364556,
 'blocks': 11.6630321858,
 'book': 2.00086596571,
 'coal': 23.7866257713,
 'doll': 4.9993625282,
 'gloves': 1.40310067709,
 'horse': 4.99527064522,
 'train': 10.0234458084}

In [168]:
REJECTED_BAGS_THRESHOLD = 0.015
NEGATIVE_REWARD = -5000
POSITIVE_REWARD = 5000
STEP_POSITIVE_REWARD = 5.0

In [169]:
def step_reward(rejected):    
    return STEP_POSITIVE_REWARD if rejected < REJECTED_BAGS_THRESHOLD else -rejected*10

def take_action(state, action):
    new_state = state.copy()
    new_state[action] += 1
    return new_state

def is_available(state, available_gifts, gift_types=GIFT_TYPES):
    for v, gift_type in zip(state, gift_types):
        if available_gifts[gift_type] - v < 0:
            return False
    return True

def update_available_gifts(available_gifts, state, gift_types=GIFT_TYPES):
    for v, gift_type in zip(state, gift_types):
        assert available_gifts[gift_type] - v >= 0, "Found state is not available : {}, {}".format(state, available_gifts)
        available_gifts[gift_type] = available_gifts[gift_type] - v
        
def state_to_str(state):
    return state.tolist().__str__()

def find_value(action, actions_values, return_index=False):
    for i, (v, a) in enumerate(actions_values):
        if action == a:
            if return_index:
                return v, i
            return v
    raise Exception("No action={} in actions_values={}".format(action, actions_values))
    
def has_action(actions_values, action, return_index=False):
    for i, (v, a) in enumerate(actions_values):
        if action == a:
            if return_index:
                return True, i
            return True
    if return_index:
        return False, None
    return False

In [125]:
NULL_ACTIONS_VALUES = [(POSITIVE_REWARD, None)]

def bag_fix_weight(state):
    out = 0
    for i, c in enumerate(state):
        out += fixed_weights[GIFT_TYPES[i]] * c
    return out

def is_too_heavy(state):
    b1 = (LIMIT_STATE - state < 0).any()
    b2 = bag_fix_weight(state) > MAX_WEIGHT
    return b1 or b2

def get_actions_values(state, action_value_function):
    state_key = state_to_str(state)
    if is_too_heavy(state):
        action_value_function[state_key]=NULL_ACTIONS_VALUES        
    actions_values = action_value_function[state_key]
    if len(actions_values) == 0:
        logging.debug("get_actions_values : Initialize random values")
        for i in range(N_TYPES):
            va = [POSITIVE_REWARD - np.random.rand(), i]            
            heapq.heappush(action_value_function[state_key], va)        
    return action_value_function[state_key]    

def set_actions_values(state, action_value_function, actions_values):
    state_key = state_to_str(state)
    action_value_function[state_key] = actions_values

def get_policy_action(state, action_value_function, epsilon=0.1):
    u = np.random.rand()
    # Get max value action
    actions_values = get_actions_values(state, action_value_function)
    max_action_value = actions_values[0]
    pr = 1.0 - epsilon + epsilon / N_TYPES
    if u <= pr:
        # Greedy
        return max_action_value[1]
    else:
        # Exploring
        if max_action_value[1] is None:
            return None
        actions = list(range(N_TYPES))
        actions.remove(max_action_value[1])
        return actions[np.random.randint(N_TYPES-1)]

In [126]:
def q_learning(goal_weight, 
               available_gifts,
               initial_state=None,
               n_episodes=10, alpha=0.75, gamma=0.95, epsilon=0.1, action_value_function=None):
    
    logging.info("--- Q-learning : goal={}, n_episodes={}".format(goal_weight, n_episodes))
    if action_value_function is None:
        logging.info("-- Reset action_value_function")
        action_value_function = defaultdict(list)
    
    best_state = None
    best_score = 0
    
    def _is_terminal_state(state, available_gifts, goal_weight):
        _is_terminal = False
        _current_reward = 0        
        _state_score, _state_score_std, _rejected, _rejected_std = score_stats((state,), count=200)
        _score_min = _state_score - _state_score_std*0.1
        _score_max = _state_score + _state_score_std*0.5            
        _rejected += _rejected_std*0.25
        if not is_available(state, available_gifts) or _rejected > 2.0*REJECTED_BAGS_THRESHOLD:                
            _current_reward = NEGATIVE_REWARD
            _is_terminal = True
            logging.debug("--->1 Episode finished with NEGATIVE reward, {}, {}, {}".format(_score_min, _score_max, _rejected))                
        elif _score_max >= MAX_WEIGHT:
            _current_reward = NEGATIVE_REWARD
            _is_terminal = True
            logging.debug("--->2 Episode finished with NEGATIVE reward, {}, {}, {}".format(_score_min, _score_max, _rejected))
        elif MAX_WEIGHT > _score_min >= goal_weight:
            _current_reward = POSITIVE_REWARD
            _is_terminal = True
            logging.debug("---> Episode finished with POSITIVE reward")
        elif _score_min < goal_weight:
            _current_reward = step_reward(_rejected)
        else:
            raise Exception("Unclassified state: {}, score_min={}, score_max={}, rejected={}".format(new_state, score_min, score_max, rejected))

        return _is_terminal, _current_reward, _score_min, _rejected
        
    
    for i in range(n_episodes):

        logging.debug("-- Episode : %i" % i)

        state = np.zeros((N_TYPES), dtype=np.uint8) if initial_state is None else initial_state.copy()        
        action = get_policy_action(state, action_value_function, epsilon=epsilon)
        logging.debug("Initial state/action: {}, {}".format(state, action))

        is_terminal, current_reward, score_min, rejected = _is_terminal_state(state, available_gifts, goal_weight)
        if is_terminal:
            logging.debug("Initial state is terminal state. Reward on state: %f" % current_reward)
            state_key = state_to_str(state)
            action_value_function[state_key] = NULL_ACTIONS_VALUES
            if current_reward == POSITIVE_REWARD:
                if best_score < score_min:
                    best_score = score_min
                    best_state = state
            continue

        episode_length = 5**N_TYPES                        
        while not is_terminal:            
            episode_length -= 1 
            if episode_length < 0:
                logging.warn('Episode length is reached, but state score is still : %f / %f' % (state_score, goal_weight))
                break
             
            new_state = take_action(state, action)
            logging.debug("New state score, reward, new_state, action : {}, {}, {} <- {}".format(score_min, current_reward, new_state, action))                

            is_terminal, current_reward, score_min, rejected = _is_terminal_state(new_state, available_gifts, goal_weight)
                    
            if is_terminal:
                set_actions_values(new_state, action_value_function, NULL_ACTIONS_VALUES)
                if current_reward == POSITIVE_REWARD:
                    if best_score < score_min:
                        best_score = score_min
                        best_state = state

    
            # Update Q(s,a)
            actions_values = get_actions_values(state, action_value_function)
            action_value, action_index = find_value(action, actions_values, return_index=True)
            # actions_values is a heap with first element being the smallest element
            # We store values in actions_values as POSITIVE_REWARD - Q(s,a)            
            v = POSITIVE_REWARD - action_value            
            new_actions_values = get_actions_values(new_state, action_value_function)            
            nv = POSITIVE_REWARD - new_actions_values[0][0] 
            t = alpha * (current_reward + gamma * nv - v)
            actions_values[action_index] = [POSITIVE_REWARD - (v + t), action]
            heapq.heapify(actions_values)
                            
            state = new_state
            action = get_policy_action(state, action_value_function, epsilon=epsilon)                        
                
    return action_value_function, best_score, best_state

In [158]:
def fill_one_bag(state, action_value_function):
    epsilon = 0.0
    action = get_policy_action(state, action_value_function, epsilon=epsilon)
    actions_values = get_actions_values(state, action_value_function)
    value = find_value(action, actions_values)
    trajectory = [(state, action, value)]
#     print "1 fill_one_bag: ", trajectory[-1]
    counter = 5**N_TYPES
    while action is not None:
        state = take_action(state, action)
        action = get_policy_action(state, action_value_function, epsilon=epsilon)
        actions_values = get_actions_values(state, action_value_function)
        value = find_value(action, actions_values)
        trajectory.append((state, action, value))
#         print "fill_one_bag: >>", trajectory[-1]

        counter -= 1
        if counter == 0:
            break
            
    if counter == 0:
        logging.warn("Counter is zero")
    return trajectory[-1][0], trajectory
        

## Single run test

In [170]:
REJECTED_BAGS_THRESHOLD = 0.05
alpha = 0.75
goal_weight = MAX_WEIGHT * alpha
print goal_weight
final_action_value_function = defaultdict(list)
#final_state = np.zeros((N_TYPES), dtype=np.uint8)

37.5


In [171]:
final_state = np.zeros((N_TYPES), dtype=np.uint8)
# final_state = np.array([2, 0, 2, 1, 0, 0, 1, 2, 0])

In [172]:
logging.getLogger().setLevel(logging.INFO)
final_action_value_function, best_score, best_state = q_learning(goal_weight, 
                                                                 AVAILABLE_GIFTS,
                                                                 initial_state=final_state,
                                                                 n_episodes=100, 
                                                                 alpha=0.75, 
                                                                 gamma=0.85, 
                                                                 epsilon=0.3, 
                                                                 action_value_function=final_action_value_function)

INFO:root:--- Q-learning : goal=37.5, n_episodes=100


In [131]:
if best_state is not None:
    print best_score, best_state, score((best_state,), return_rejected=True), 2.0*REJECTED_BAGS_THRESHOLD

In [132]:
best_state = [0, 0, 2, 2, 0, 0, 1, 0, 0]

In [133]:
best_state, score_stats((best_state,), count=200)

([0, 0, 2, 2, 0, 0, 1, 0, 0],
 (29.180609865663264, 5.0964871143577115, 0.0, 0.0))

In [65]:
LIMIT_STATE

array([ 34,  14,   8, 218,   3,  26, 184,  30,  28], dtype=uint8)

In [149]:
bag, trajectory = fill_one_bag(final_state, final_action_value_function)
print bag, score((bag,), return_rejected=True)
print trajectory

1 fill_one_bag:  (array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8), 0, 995.34016608969)
fill_one_bag: >> (array([1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8), 2, 995.69410124041985)
fill_one_bag: >> (array([1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=uint8), 0, 995.9849096793112)
fill_one_bag: >> (array([2, 0, 1, 0, 0, 0, 0, 0, 0], dtype=uint8), 2, 996.3545364008723)
fill_one_bag: >> (array([2, 0, 2, 0, 0, 0, 0, 0, 0], dtype=uint8), 0, 996.7940490685389)
fill_one_bag: >> (array([3, 0, 2, 0, 0, 0, 0, 0, 0], dtype=uint8), 0, 997.1436422491814)
fill_one_bag: >> (array([4, 0, 2, 0, 0, 0, 0, 0, 0], dtype=uint8), 6, 997.6601841822961)
fill_one_bag: >> (array([4, 0, 2, 0, 0, 0, 1, 0, 0], dtype=uint8), 6, 998.3982929123549)
fill_one_bag: >> (array([4, 0, 2, 0, 0, 0, 2, 0, 0], dtype=uint8), 3, 999.3286978893657)
fill_one_bag: >> (array([4, 0, 2, 1, 0, 0, 2, 0, 0], dtype=uint8), 8, 999.0488163727546)
fill_one_bag: >> (array([4, 0, 2, 1, 0, 0, 2, 0, 1], dtype=uint8), 8, 999.1450093691924)
fill_one_bag: >> (arra

In [150]:
final_action_value_function

defaultdict(list,
            {'[0, 0, 0, 0, 0, 0, 0, 0, 0]': [[995.34016608969, 0],
              [996.5328291646676, 3],
              [997.3876504183734, 1],
              [996.6821013883769, 2],
              [999.5691663045352, 4],
              [998.699015502261, 5],
              [997.9247511033662, 6],
              [997.7680372537797, 7],
              [997.7511074033719, 8]],
             '[0, 0, 0, 0, 0, 0, 0, 0, 1]': [[997.9992210043721, 2],
              [998.5792539903146, 8],
              [998.5570033308948, 3],
              [999.0345824777986, 4],
              [999.17597549108, 1],
              [999.5452655714669, 5],
              [999.1317325460811, 6],
              [999.7544154606327, 7],
              [999.0671845087924, 0]],
             '[0, 0, 0, 0, 0, 0, 0, 0, 2]': [[999.1124480421984, 5],
              [999.510668885117, 8],
              [999.397163703248, 6],
              [999.5184679816986, 7],
              [999.9700511589672, 4],
              [999.9

In [ ]:
# for count in [100, 200, 300]:
#     sc = []
#     sc2 = []
#     for i in range(200):
#         s, r = score((best_state,), return_rejected=True, count=count)
#         sc.append(s)
#         rr.append(r)

#     plt.figure(figsize=(12,4))
#     plt.subplot(131)    
#     plt.plot(sc)
#     plt.subplot(132)
#     plt.plot(rr)

## Action-value function estimation

In [174]:
REJECTED_BAGS_THRESHOLD = 0.06
alpha = 0.72
goal_weight = MAX_WEIGHT * alpha
print goal_weight

#filled_bags = np.zeros((N_BAGS, N_TYPES), dtype=np.uint8)
final_action_value_function = defaultdict(list)
available_gifts = deepcopy(AVAILABLE_GIFTS)
bag_index = 0
found_goal_states = []

36.0


In [ ]:
logging.getLogger().setLevel(logging.WARN)
n_episodes = 250

last_score_computation = -1
limit_fails = 20
while bag_index < N_BAGS:
    
    print("Found goal bags : ", bag_index, "/", N_BAGS)
    
    final_action_value_function, best_score, best_state = q_learning(goal_weight, 
                                                                 available_gifts,
                                                                 n_episodes=n_episodes, 
                                                                 alpha=0.75, 
                                                                 gamma=0.85, 
                                                                 epsilon=0.33, 
                                                                 action_value_function=final_action_value_function)
    if best_score > 0:
        print("- Got a result : ", best_score, best_state)
        # update_available_gifts(available_gifts, best_state, GIFT_TYPES)
        
        if len(found_goal_states) == 0 or (found_goal_states[-1] != best_state).any():
            found_goal_states.append(best_state)        
        bag_index += 1
        
        limit_fails = 20
    else:
        print("No best state found")
        limit_fails -= 1
        
        
#     if bag_index > 0 and (bag_index % 20) == 0 and last_score_computation < bag_index:
#             s, r = score(filled_bags, return_rejected=True)
#             print(">>> Current score: ", s, s * N_BAGS *1.0 / bag_index, "rejected=", r)
#             last_score_computation = bag_index

#     if bag_index > 0 and (bag_index % 30) == 0 and last_score_computation < bag_index:
#         print(">>> Currently available gifts : ", [(k, available_gifts[k]) for k in GIFT_TYPES])
#         last_score_computation = bag_index
        
    if limit_fails == 0:
        break

('Found goal bags : ', 0, '/', 1000)
('- Got a result : ', 37.031371811123272, array([0, 0, 2, 1, 0, 1, 1, 1, 0], dtype=uint8))
('Found goal bags : ', 1, '/', 1000)
('- Got a result : ', 37.813477630759358, array([4, 0, 2, 0, 0, 0, 0, 1, 0], dtype=uint8))
('Found goal bags : ', 2, '/', 1000)


In [164]:
len(found_goal_states), found_goal_states


(31,
 [array([1, 0, 1, 0, 0, 1, 0, 2, 0], dtype=uint8),
  array([1, 0, 1, 0, 0, 1, 1, 3, 0], dtype=uint8),
  array([0, 0, 1, 0, 0, 2, 1, 1, 0], dtype=uint8),
  array([4, 0, 0, 1, 0, 1, 3, 3, 0], dtype=uint8),
  array([4, 0, 0, 1, 0, 3, 0, 2, 0], dtype=uint8),
  array([2, 0, 2, 0, 0, 1, 1, 0, 0], dtype=uint8),
  array([1, 0, 2, 0, 0, 2, 0, 0, 0], dtype=uint8),
  array([1, 0, 1, 2, 0, 2, 4, 0, 0], dtype=uint8),
  array([2, 0, 1, 0, 0, 1, 3, 2, 0], dtype=uint8),
  array([1, 0, 0, 1, 0, 4, 0, 1, 0], dtype=uint8),
  array([1, 0, 0, 0, 0, 4, 3, 2, 0], dtype=uint8),
  array([2, 0, 1, 3, 0, 1, 1, 0, 0], dtype=uint8),
  array([2, 0, 2, 1, 0, 1, 1, 0, 0], dtype=uint8),
  array([1, 0, 1, 2, 0, 2, 0, 0, 0], dtype=uint8),
  array([2, 0, 1, 1, 0, 1, 2, 0, 0], dtype=uint8),
  array([1, 0, 1, 3, 0, 1, 4, 1, 0], dtype=uint8),
  array([2, 0, 1, 1, 0, 1, 2, 2, 0], dtype=uint8),
  array([2, 0, 1, 2, 0, 1, 3, 0, 0], dtype=uint8),
  array([2, 0, 1, 0, 0, 2, 0, 1, 0], dtype=uint8),
  array([1, 0, 1, 2, 0, 1,

In [165]:
len(final_action_value_function)

6314

## Bag filling with estimated action-value function

In [166]:
final_state = np.zeros((N_TYPES), dtype=np.uint8)
bag, trajectory = fill_one_bag(final_state, final_action_value_function)
print bag, score((bag,), return_rejected=True)
print trajectory

[7 1 0 4 0 2 3 0 0] (14.201008896022406, 0.68000000000000005)
[(array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8), 3, 993.83937128904131), (array([0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8), 5, 993.928711865791), (array([0, 0, 0, 1, 0, 1, 0, 0, 0], dtype=uint8), 0, 994.03525365562768), (array([1, 0, 0, 1, 0, 1, 0, 0, 0], dtype=uint8), 5, 994.15971824394921), (array([1, 0, 0, 1, 0, 2, 0, 0, 0], dtype=uint8), 3, 994.31308716440981), (array([1, 0, 0, 2, 0, 2, 0, 0, 0], dtype=uint8), 3, 994.48647696653518), (array([1, 0, 0, 3, 0, 2, 0, 0, 0], dtype=uint8), 0, 994.69193975016094), (array([2, 0, 0, 3, 0, 2, 0, 0, 0], dtype=uint8), 6, 994.9504394009396), (array([2, 0, 0, 3, 0, 2, 1, 0, 0], dtype=uint8), 0, 995.2554514657432), (array([3, 0, 0, 3, 0, 2, 1, 0, 0], dtype=uint8), 6, 995.60731311016832), (array([3, 0, 0, 3, 0, 2, 2, 0, 0], dtype=uint8), 0, 996.01759242240701), (array([4, 0, 0, 3, 0, 2, 2, 0, 0], dtype=uint8), 0, 996.54904307074446), (array([5, 0, 0, 3, 0, 2, 2, 0, 0], dtype=uint8), 0, 