# Statistical analysisa and examples

In [1]:
import sys
sys.path.append('../common')
from utils import weight3 as weight_fn, weight_by_index
from utils import bag_weight, score, mean_n_sigma, score_stats
from utils import MAX_WEIGHT, AVAILABLE_GIFTS, GIFT_TYPES, N_TYPES, N_BAGS

from copy import deepcopy
from collections import defaultdict

import numpy as np
np.random.seed(2017)
import matplotlib.pyplot as plt
%matplotlib inline

/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [2]:
N_TRIALS = 10000
GIFT_WEIGHTS = np.zeros((N_TRIALS, N_TYPES))
for index in range(N_TYPES):
    GIFT_WEIGHTS[:, index] = [weight_by_index(index) for i in range(10000)]

In [3]:
def find_n(weights):
    best_mean_score = 0
    best_n = 0
    for n in range(1, 500):
        mask = weights * n < MAX_WEIGHT
        if not mask.any():
            break
        score = np.sum(weights[mask] * n) * 1.0 / len(weights)  
        if score > best_mean_score:
            best_mean_score = score
            best_n = n
            
    return best_n, best_mean_score

LIMIT_NB_GIFTS = np.zeros((N_TYPES), dtype=np.uint8)

for index in range(N_TYPES):
    n, s = find_n(GIFT_WEIGHTS[:,index])
    print GIFT_TYPES[index], index, n, s
    LIMIT_NB_GIFTS[index] = n + 1

ball 0 20 37.6322158867
bike 1 2 20.7807671664
blocks 2 3 31.0021348597
book 3 13 14.7958669438
coal 4 1 23.2965570426
doll 5 6 25.2286629621
gloves 6 50 17.5340524804
horse 7 6 27.3275000842
train 8 3 25.2152724369


In [4]:
LIMIT_NB_GIFTS, np.prod(LIMIT_NB_GIFTS)

(array([21,  3,  4, 14,  2,  7, 51,  7,  4], dtype=uint8), 70531776)

In [5]:
def compute_score(state):
    s = np.sum(GIFT_WEIGHTS * state, axis=1)
    mask = s < MAX_WEIGHT
    rejected = (N_TRIALS - np.sum(mask))*1.0 / N_TRIALS
    score = np.sum(s[mask]) * 1.0 / N_TRIALS
    return score, rejected


state = np.zeros((N_TYPES), dtype=np.uint8)
state[1] = 1
compute_score(state)

(19.958184702872448, 0.0016000000000000001)

In [6]:
alpha = 0.745
goal_weight = MAX_WEIGHT * alpha
print goal_weight

37.25


In [7]:
LIMIT_NB_GIFTS

array([21,  3,  4, 14,  2,  7, 51,  7,  4], dtype=uint8)

In [8]:
def huge_loop2(rejected_threshold):
    scores = []
    for n0 in range(LIMIT_NB_GIFTS[0]):
        print "n0: ", n0, "/", LIMIT_NB_GIFTS[0]
        state = np.array([n0, 0, 0, 0, 0, 0, 0, 0, 0])
        s, r = compute_score(state)
        if r > rejected_threshold:
            break
        for n1 in range(LIMIT_NB_GIFTS[1]):
            state = np.array([n0, n1, 0, 0, 0, 0, 0, 0, 0])
            s, r = compute_score(state)
            if r > rejected_threshold:
                break
            for n2 in range(LIMIT_NB_GIFTS[2]):
                state = np.array([n0, n1, n2, 0, 0, 0, 0, 0, 0])
                s, r = compute_score(state)
                if r > rejected_threshold:
                    break
                for n3 in range(LIMIT_NB_GIFTS[3]):
                    state = np.array([n0, n1, n2, n3, 0, 0, 0, 0, 0])
                    s, r = compute_score(state)
                    if r > rejected_threshold:
                        break
                    for n4 in range(LIMIT_NB_GIFTS[4]):
                        state = np.array([n0, n1, n2, n3, n4, 0, 0, 0, 0])
                        s, r = compute_score(state)
                        if r > rejected_threshold:
                            break                        
                        for n5 in range(LIMIT_NB_GIFTS[5]):
                            state = np.array([n0, n1, n2, n3, n4, n5, 0, 0, 0])
                            s, r = compute_score(state)
                            if r > rejected_threshold:
                                break                        
                            for n6 in range(LIMIT_NB_GIFTS[6]):
                                state = np.array([n0, n1, n2, n3, n4, n5, n6, 0, 0])
                                s, r = compute_score(state)
                                if r > rejected_threshold:
                                    break                        
                                for n7 in range(LIMIT_NB_GIFTS[7]):
                                    state = np.array([n0, n1, n2, n3, n4, n5, n6, n7, 0])
                                    s, r = compute_score(state)
                                    if r > rejected_threshold:
                                        break                        
                                    for n8 in range(LIMIT_NB_GIFTS[8]):
                                        state = np.array([n0, n1, n2, n3, n4, n5, n6, n7, n8])
                                        s, r = compute_score(state)
                                        if r > rejected_threshold:
                                            break                                    
                                        scores.append((state, s, r))
    return scores

In [10]:
import os
filename = "scores_r_075.npy"
if os.path.exists(filename):
    scores = np.load(filename)
else:
    scores = huge_loop2(0.75)
    scores = np.array(scores)
    # Save result
    np.save("scores_r_075.npy", scores)

In [12]:
# alpha = 0.745
# goal_weight = MAX_WEIGHT * alpha
# print goal_weight
# mask = scores[:, 1] > goal_weight
# # len(scores[mask]), scores[mask][:10, :]

In [91]:
def has_min_nb_gifts(state):
    return np.sum(state) >= 3 

def is_available(state, available_gifts, gift_types=GIFT_TYPES):
    for v, gift_type in zip(state, gift_types):
        if available_gifts[gift_type] - v < 0:
            return False
    return True

def update_available_gifts(available_gifts, state, gift_types=GIFT_TYPES):
    for v, gift_type in zip(state, gift_types):
        assert available_gifts[gift_type] - v >= 0, "Found state is not available : {}, {}".format(state, available_gifts)
        available_gifts[gift_type] = available_gifts[gift_type] - v

        
def fill_bags3(sorted_scores, available_gifts):
    filled_bags = np.zeros((N_BAGS, N_TYPES), dtype=np.uint8)    
    last_score_computation = -1
    good_bag_index = 0
    bag_index = 0
    
    stop_loop = len(sorted_scores)
    n_start = 0
    next_group = False
    
    state = sorted_scores[good_bag_index, 0]
    current_n = np.sum(state)
    while bag_index < N_BAGS and stop_loop > 0:
        
#         good_bag_index = np.random.randint(len(sorted_scores))        
        if is_available(state, available_gifts) and has_min_nb_gifts(state):
#             print "bag index : ", bag_index, stop_loop        
            update_available_gifts(available_gifts, state, GIFT_TYPES)
            filled_bags[bag_index, :] = state
            bag_index += 1
            stop_loop = len(sorted_scores)            
        else:
            stop_loop -= 1            
        
        good_bag_index += 1
        state = sorted_scores[good_bag_index, 0]
        n = np.sum(state)
        if n < current_n:
            good_bag_index = n_start
        

        if good_bag_index < len(sorted_scores)-1:
            good_bag_index += 1
        else:
            good_bag_index = n_start
                
        if bag_index > 0 and (bag_index % 100) == 0 and last_score_computation < bag_index:
            s, r = score(filled_bags, return_rejected=True)
            print(bag_index, ">>> Current score: ", s, s * N_BAGS *1.0 / bag_index, "rejected=", r)
            last_score_computation = bag_index

        if bag_index > 0 and (bag_index % 150) == 0 and last_score_computation < bag_index:
            print(bag_index, ">>> Currently available gifts : ", [(k, available_gifts[k]) for k in GIFT_TYPES])
            last_score_computation = bag_index
    
    print "good_bag_index", good_bag_index
    return filled_bags


def fill_bags(sorted_scores, available_gifts):
    filled_bags = np.zeros((N_BAGS, N_TYPES), dtype=np.uint8)    
    last_score_computation = -1
    good_bag_index = 0
    bag_index = 0
    
    while bag_index < N_BAGS and good_bag_index < len(sorted_scores):
    
        state = sorted_scores[good_bag_index, 0]
        if is_available(state, available_gifts) and has_min_nb_gifts(state):
#             print "bag index : ", bag_index, stop_loop        
            update_available_gifts(available_gifts, state, GIFT_TYPES)
            filled_bags[bag_index, :] = state
            bag_index += 1
        else:
            good_bag_index += 1
                
        if bag_index > 0 and (bag_index % 100) == 0 and last_score_computation < bag_index:
            s, r = score(filled_bags, return_rejected=True)
            print(bag_index, ">>> Current score: ", s, s * N_BAGS *1.0 / bag_index, "rejected=", r)
            last_score_computation = bag_index

        if bag_index > 0 and (bag_index % 150) == 0 and last_score_computation < bag_index:
            print(bag_index, ">>> Currently available gifts : ", [(k, available_gifts[k]) for k in GIFT_TYPES])
            last_score_computation = bag_index
    
    print "good_bag_index", good_bag_index
    return filled_bags

In [14]:
import pandas as pd
df_scores = pd.DataFrame(data=scores, columns=['state', 'score', 'rejected'])
df_scores.head()

state    score rejected
0  [0, 0, 0, 0, 0, 0, 0, 0, 0]        0        0
1  [0, 0, 0, 0, 0, 0, 0, 0, 1]  9.96169        0
2  [0, 0, 0, 0, 0, 0, 0, 0, 2]  19.8436   0.0015
3  [0, 0, 0, 0, 0, 0, 0, 0, 3]  24.8407   0.0882
4  [0, 0, 0, 0, 0, 0, 0, 1, 0]  5.02266        0

In [45]:
df_scores.loc[:, 'n'] = df_scores['state'].apply(np.sum)

In [78]:
def compute_n_bags(state, available_gifts=AVAILABLE_GIFTS):
    out = 1000
    for i, v in enumerate(state):
        if v > 0:
            n = int(np.floor(available_gifts[GIFT_TYPES[i]] / v))
            out = min(out, n)
    return out
    
# compute_n_bags(np.array([19, 0, 0, 0, 0, 0, 1, 0, 0]), AVAILABLE_GIFTS)
df_scores.loc[:, 'n_bags'] = df_scores['state'].apply(compute_n_bags)

In [86]:
df_scores.loc[:, 'n_bags_x_score'] = df_scores['score'] * df_scores['n_bags']

In [137]:
df_scores.loc[:, 'rejected_x_n'] = df_scores['rejected'] * df_scores['n'] * df_scores['n_bags'] / N_BAGS

In [316]:
df_sorted_scores = df_scores.sort_values(['score'], ascending=False)

In [325]:
def to_remove(s):
    a = np.array([1, 0, 1, 0, 0, 1, 1, 1, 0])
#     if (s == a).all():
#         return False    
    res = a * s
    return np.sum(res) != 0

In [313]:
a = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0])
b = np.array([0, 0, 1, 2, 0, 1, 0, 1, 1])
# b = (b > 0).astype(np.int)
res = a * b
res, np.sum(res) == 0

(array([0, 0, 0, 0, 0, 0, 0, 0, 0]), True)

In [314]:
AVAILABLE_GIFTS

{'ball': 1100,
 'bike': 500,
 'blocks': 1000,
 'book': 1200,
 'coal': 166,
 'doll': 1000,
 'gloves': 200,
 'horse': 1000,
 'train': 1000}

In [328]:
s, n, r = 25, 1201, 0.75
df = df_sorted_scores[(df_sorted_scores['n_bags'] < n) & (df_sorted_scores['rejected'] < r) & (df_sorted_scores['score'] > s)]
df.loc[:, 'to_remove'] = df['state'].apply(to_remove)
df = df[(df['to_remove'] == False)] 
df.shape, df['score'].min(), df['score'].max(), df.head(20)

((14, 8),
 25.036970528889452,
 29.182936774532603,
                              state    score rejected  n  n_bags  \
 83495  [0, 1, 0, 2, 0, 0, 0, 0, 1]  29.1829   0.0884  4     500   
 82126  [0, 1, 0, 1, 0, 0, 0, 0, 1]  29.0212   0.0566  3     500   
 84635  [0, 1, 0, 3, 0, 0, 0, 0, 1]  28.5514   0.1323  5     400   
 80479  [0, 1, 0, 0, 0, 0, 0, 0, 1]  28.0894   0.0377  2     500   
 85593  [0, 1, 0, 4, 0, 0, 0, 0, 1]  27.5771   0.1789  6     300   
 86399  [0, 1, 0, 5, 0, 0, 0, 0, 1]  26.4415   0.2249  7     240   
 80480  [0, 1, 0, 0, 0, 0, 0, 0, 2]  26.2994    0.236  3     500   
 82127  [0, 1, 0, 1, 0, 0, 0, 0, 2]  25.3452   0.2837  4     500   
 12000  [0, 0, 0, 2, 0, 0, 0, 0, 3]  25.3153   0.1468  5     333   
 6303   [0, 0, 0, 1, 0, 0, 0, 0, 3]  25.2831   0.1147  4     333   
 87088  [0, 1, 0, 6, 0, 0, 0, 0, 1]  25.2286   0.2693  8     200   
 86398  [0, 1, 0, 5, 0, 0, 0, 0, 0]  25.1407   0.0838  6     240   
 85592  [0, 1, 0, 4, 0, 0, 0, 0, 0]  25.1081   0.0529  5     300

In [216]:
print "\n\n--- Start bags filling with : min_score=", s, "rejected=", r
# df = df_sorted_scores[df_sorted_scores['score'] > s]
print "\n---", df.shape, df['score'].min(), df['score'].max(), df.head()
available_gifts = deepcopy(AVAILABLE_GIFTS)
print "\n--------------\n"
filled_bags = fill_bags(df.as_matrix(), available_gifts)



--- Start bags filling with : min_score= 30 rejected= 0.5

--- (7608, 8) 30.0000967414 38.4634778233                               state    score rejected  n  n_bags  \
214458  [2, 0, 1, 1, 0, 1, 0, 1, 1]  35.5703   0.0401  7     550   
90314   [0, 1, 1, 0, 0, 0, 0, 1, 0]  30.8708   0.1089  3     500   
236172  [2, 1, 1, 0, 0, 0, 0, 0, 0]  30.8404   0.0918  4     500   
236427  [2, 1, 1, 1, 0, 0, 0, 0, 0]  30.7583   0.1281  5     500   
90521   [0, 1, 1, 0, 0, 1, 0, 0, 0]   30.749   0.1114  3     500   

       n_bags_x_score rejected_x_n to_remove  
214458        19563.7     0.154385     False  
90314         15435.4      0.16335     False  
236172        15420.2       0.1836     False  
236427        15379.1      0.32025     False  
90521         15374.5       0.1671     False  

--------------

(100, '>>> Current score: ', 3559.0361310438543, 35590.361310438544, 'rejected=', 4.1200000000000001)
(150, '>>> Currently available gifts : ', [('ball', 800), ('bike', 500), ('blocks', 850

In [180]:
print score(filled_bags, return_rejected=True), available_gifts

(21116.350252714969, 28.530000000000001) {'horse': 400, 'ball': 500, 'blocks': 400, 'doll': 400, 'train': 400, 'coal': 166, 'bike': 500, 'gloves': 200, 'book': 0}


In [229]:
def custom_fill_bags(sorted_scores, available_gifts):
    filled_bags = np.zeros((N_BAGS, N_TYPES), dtype=np.uint8)    
    last_score_computation = -1
    good_bag_index = 0
    bag_index = 0
    
#     print "-- stage 1"
#     while bag_index < N_BAGS-100:    
#         state = sorted_scores[0, 0]
#         if is_available(state, available_gifts) and has_min_nb_gifts(state):
# #             print "bag index : ", bag_index, stop_loop        
#             update_available_gifts(available_gifts, state, GIFT_TYPES)
#             filled_bags[bag_index, :] = state
#             bag_index += 1
                
#         if bag_index > 0 and (bag_index % 100) == 0 and last_score_computation < bag_index:
#             s, r = score(filled_bags, return_rejected=True)
#             print(bag_index, ">>> Current score: ", s, s * N_BAGS *1.0 / bag_index, "rejected=", r)
#             last_score_computation = bag_index

#         if bag_index > 0 and (bag_index % 150) == 0 and last_score_computation < bag_index:
#             print(bag_index, ">>> Currently available gifts : ", [(k, available_gifts[k]) for k in GIFT_TYPES])
#             last_score_computation = bag_index
    
    print "-- stage 2"
    good_bag_index = 1
    while bag_index < N_BAGS and good_bag_index < len(sorted_scores):
    
        state = sorted_scores[good_bag_index, 0]
        if is_available(state, available_gifts) and has_min_nb_gifts(state):
#             print "bag index : ", bag_index, stop_loop        
            update_available_gifts(available_gifts, state, GIFT_TYPES)
            filled_bags[bag_index, :] = state
            bag_index += 1
        else:
            good_bag_index += 1
                
        if bag_index > 0 and (bag_index % 100) == 0 and last_score_computation < bag_index:
            s, r = score(filled_bags, return_rejected=True)
            print(bag_index, ">>> Current score: ", s, s * N_BAGS *1.0 / bag_index, "rejected=", r)
            last_score_computation = bag_index

        if bag_index > 0 and (bag_index % 150) == 0 and last_score_computation < bag_index:
            print(bag_index, ">>> Currently available gifts : ", [(k, available_gifts[k]) for k in GIFT_TYPES])
            last_score_computation = bag_index
    
    
    
    
    print "good_bag_index", good_bag_index
    return filled_bags

In [284]:
score(([0, 2, 0, 0, 0, 0, 1, 0, 0],), return_rejected=True)

(28.133028727270752, 0.25)

In [292]:
score(([0, 0, 0, 0, 1, 0, 2, 0, 0],), return_rejected=True)

(23.03569290913374, 0.040000000000000001)

In [287]:
custom_states = np.array([
    [[1, 0, 1, 1, 0, 1, 0, 1, 1], 34.5248, 0.0223],
    [[0, 0, 0, 0, 1, 0, 2, 0, 0], 22.731160986729527, 0.05],
])

In [232]:
filled_bags

array([[0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 2, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [230]:
print "\n\n--- Start bags filling with : min_score=", s, "rejected=", r
# df = df_sorted_scores[df_sorted_scores['score'] > s]
print "\n---", custom_states.shape, custom_states[:10,:]
available_gifts = deepcopy(AVAILABLE_GIFTS)
print "\n--------------\n"
filled_bags = custom_fill_bags(custom_states, available_gifts)



--- Start bags filling with : min_score= 30 rejected= 0.5

--- (2, 3) [[[1, 0, 1, 1, 0, 1, 0, 1, 1] 34.5248 0.0223]
 [[0, 0, 0, 0, 1, 0, 2, 0, 0] 22.731160986729527 0.05]]

--------------

-- stage 2
(100, '>>> Current score: ', 2350.8876627271939, 23508.87662727194, 'rejected=', 5.5199999999999996)
good_bag_index 2


In [224]:
print "\n\n--- Start bags filling with : min_score=", s, "rejected=", r
# df = df_sorted_scores[df_sorted_scores['score'] > s]
print "\n---", custom_states.shape, custom_states[:10,:]
available_gifts = deepcopy(AVAILABLE_GIFTS)
print "\n--------------\n"
filled_bags = custom_fill_bags(custom_states, available_gifts)



--- Start bags filling with : min_score= 30 rejected= 0.5

--- (2, 3) [[[1, 0, 1, 1, 0, 1, 0, 1, 1] 34.5248 0.0223]
 [[0, 0, 0, 0, 1, 0, 2, 0, 0] 22.731160986729527 0.05]]

--------------

-- stage 1
(100, '>>> Current score: ', 3456.4097109030072, 34564.097109030074, 'rejected=', 2.04)
(150, '>>> Currently available gifts : ', [('ball', 950), ('bike', 500), ('blocks', 850), ('book', 1050), ('coal', 166), ('doll', 850), ('gloves', 200), ('horse', 850), ('train', 850)])
(200, '>>> Current score: ', 6924.4221713364605, 34622.110856682302, 'rejected=', 4.2400000000000002)
(300, '>>> Current score: ', 10369.626637567962, 34565.422125226542, 'rejected=', 6.5099999999999998)
(400, '>>> Current score: ', 13849.590864198588, 34623.97716049647, 'rejected=', 8.8800000000000008)
(450, '>>> Currently available gifts : ', [('ball', 650), ('bike', 500), ('blocks', 550), ('book', 750), ('coal', 166), ('doll', 550), ('gloves', 200), ('horse', 550), ('train', 550)])
(500, '>>> Current score: ', 17272

In [231]:
34584.064649662694 - 31069.154712598054

3514.90993706464

In [40]:
def to_submission(state, available_gifts, gift_types):
    n_gifts = [available_gifts[t] for t in gift_types]
    output = []
    for bag in state:
        o = []
        for index, count in enumerate(bag):   
            gift_type = gift_types[index]
            for i in range(count):
                v = n_gifts[index] - 1
                assert v >= 0, "Gift index is negative"
                o.append(gift_type + '_%i' % v)
                n_gifts[index] -= 1
        output.append(o)  
    return output

def write_submission(state, filename):
    with open(filename, 'w') as w:
        w.write("Gifts\n")
        for bag in state:
            w.write(' '.join(bag) + '\n')
    


In [41]:
from datetime import datetime
submission_file = '../results/submission_' + \
                  str(datetime.now().strftime("%Y-%m-%d-%H-%M")) + \
                  '.csv'  
        
submission = to_submission(filled_bags, AVAILABLE_GIFTS, GIFT_TYPES)    
write_submission(submission, submission_file)        

### Some results 

- submission_2017-01-29-13-59.csv
- random shuffle, s = 22
- Local : 33224.557601849941, 84.790000000000006
- Kaggle : 33534.45962
